import = ["./catppuccin-mocha.yml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "tmux-256color"

[font]
builtin_box_drawing = true
size = 14.0

[font.bold]
family = "GeistMono Nerd Font Mono"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "GeistMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "GeistMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 0
y = 1

[window]
decorations = "full"
dynamic_title = true
opacity = 0.9
# option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

# [window.dimensions]
# columns = 150
# lines = 38

[window.padding]
x = 10
y = 26

# [window.position]
# x = 20
# y = 75
